welcomescreen=yes
showwindowed=yes
showfullscreen=yes
keybindings=no
vidscale=no
scalewindowed=1.5
scalefullscreen=1.5
scaleforcedwindow=1.5
showonpause=yes
bottomhover=yes
raisesubswithosc=no
showtitle=yes
showdescription=yes
showfilesize=yes
dateformat=%Y-%m-%d
seekbarfg_color=7F007F
hovereffect=no
jumpamount=5
jumpiconnumber=yes
volumecontrol=yes
volumecontroltype=linear
showjump=yes
showskip=yes
compactmode=no
showloop=yes
showontop=yes
showinfo=yes
downloadbutton=yes
downloadpath=C:\Users\Admin\Videos
showyoutubecomments=yes
commentsdownloadpath=C:\Users\Admin\Documents
ytdlpQuality='-f bestvideo[vcodec^=avc][ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'