bottomhover=yes
dateformat=%Y-%m-%d
hovereffect=yes
keybindings=no
raisesubswithosc=no
scaleforcedwindow=1.25
scalefullscreen=1.25
scalewindowed=1.25
seekbarbg_color=FFFFFF
seekbarfg_color=800080
showdescription=yes
showfilesize=yes
vidscale=no
volumecontrol=yes
volumecontroltype=linear
welcomescreen=yes