welcomescreen=yes
showwindowed=yes
showfullscreen=yes
keybindings=no
vidscale=no
scalewindowed=1
scalefullscreen=1
scaleforcedwindow=1
showonpause=yes
bottomhover=yes
raisesubswithosc=no
showtitle=yes
showdescription=yes
showfilesize=yes
font=Ubuntu
dateformat=%Y-%m-%d
seekbarfg_color=800080
hovereffect=no
jumpamount=5
jumpiconnumber=5
volumecontrol=yes
volumecontroltype=linear
showjump=yes
showskip=yes
compactmode=no
showloop=yes
showontop=yes
showinfo=yes
downloadbutton=yes
downloadpath=C:\Users\Auzatte\Videos
showyoutubecomments=yes
commentsdownloadpath=C:\Users\Auzatte\Documents
ytdlpQuality=best